// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: deleteFollow.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const deleteFollowRecord = `-- name: DeleteFollowRecord :one
DELETE FROM feed_follows
WHERE user_id = $1 AND feed_id = $2
RETURNING id, created_at, updated_at, user_id, feed_id
`

type DeleteFollowRecordParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) DeleteFollowRecord(ctx context.Context, arg DeleteFollowRecordParams) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, deleteFollowRecord, arg.UserID, arg.FeedID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
