// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: getFeeds.sql

package database

import (
	"context"
	"database/sql"
)

const getFeeds = `-- name: GetFeeds :many
SELECT feeds.name AS feed_name,
feeds.url AS url,
users.name AS user_name
FROM feeds
LEFT JOIN users
ON feeds.user_id = users.id
ORDER BY users.name
`

type GetFeedsRow struct {
	FeedName string
	Url      string
	UserName sql.NullString
}

func (q *Queries) GetFeeds(ctx context.Context) ([]GetFeedsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeeds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedsRow
	for rows.Next() {
		var i GetFeedsRow
		if err := rows.Scan(&i.FeedName, &i.Url, &i.UserName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
