// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: markFeedFetched.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const markFeedFetchedTime = `-- name: MarkFeedFetchedTime :exec
UPDATE feeds
SET last_fetched_at = $1,
updated_at = $2
WHERE id = $3
`

type MarkFeedFetchedTimeParams struct {
	LastFetchedAt sql.NullTime
	UpdatedAt     time.Time
	ID            uuid.UUID
}

func (q *Queries) MarkFeedFetchedTime(ctx context.Context, arg MarkFeedFetchedTimeParams) error {
	_, err := q.db.ExecContext(ctx, markFeedFetchedTime, arg.LastFetchedAt, arg.UpdatedAt, arg.ID)
	return err
}
